spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library1
  shell:
    interactive:
      enabled: true

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.ageev.hw08springdatamongodb.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR
